#! /bin/sh
### BEGIN INIT INFO
# Provides:          temperature
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: record temperature
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "mbutki: temp start"
    nohup python /home/mbutki/pi_projects/sensorRead/readTemperature_SHT31-D.py &
    log_end_msg $?
    exit 0
    ;;
  stop)
    pkill -f /home/mbutki/pi_projects/sensorRead/readTemperature_SHT31-D.py
    log_begin_msg "mbutki: temp stop"
    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/<your script> {start|stop}"
    exit 1
    ;;
esac
